/* UI */
export const UI_SET_WEB3_MESSAGE = 'UI_SET_WEB3_MESSAGE';
export const UI_SET_WEB3_TYPE = 'UI_SET_WEB3_TYPE';
export const UI_SET_ERROR_MESSAGE = 'UI_SET_ERROR_MESSAGE';
export const UI_CLOSE_ERROR_DIALOG = 'UI_CLOSE_ERROR_DIALOG';

/* USER */
export const USER_SET_USER_INFO = 'USER_SET_USER_INFO';
export const USER_SET_LOCAL_WALLET = 'USER_SET_LCOAL_WALLET';
export const USER_SET_IS_REGISTERED_NEEDED = 'USER_SET_IS_REGISTERED_NEEDED';
